knitr::opts_chunk$set(echo = TRUE)
dataset = read.csv("/home/sanket/CollegeNotes/EDA/Datasets/stack-overflow-developer-survey-2022/survey_results_schema.csv")
names(dataset)
search()
# install.packages("ggplot2")
library(ggplot2)
library(dplyr)
search()
head(dataset)
str(dataset)
dim(dataset)
names(dataset)
str(dataset)
print(as.factor(dataset$qid))
library(dplyr)
data_mod = dataset %>% mutate(qfreq = qid)
data_mod = data_mod %>% select(qid,qfreq,qname,question,force_resp,type,selector)
head(data_mod)
questionfreq = as.factor(data_mod$qfreq)
levels(questionfreq)
table(questionfreq)
questionfreq = as.data.frame(table(questionfreq))
print(questionfreq)
data_mod %>% filter(qid == "QID289")
str(dataset)
str(data_mod)
library(ggplot2)
class(questionfreq$questionfreq)
class(questionfreq$Freq)
questionfreq$questionfreq = as.numeric(questionfreq$questionfreq)
questionfreq$questionfreq
table(questionfreq)
questionfreq = as.data.frame(questionfreq)
head(questionfreq)
questionfreq = questionfreq %>% rename(qid = questionfreq)
head(questionfreq)
str(dataset)
typefreq = as.factor(data_mod$type)
typefreq = as.data.frame(table(typefreq))
typefreq
head(data_mod)
ggplot(questionfreq , aes(x= qid , y = Freq)) + geom_line()
typefreq = typefreq %>% rename( type = typefreq )
typefreq$type = as.numeric(typefreq$type)
print(typefreq)
ggplot(typefreq , aes( x = type ,  y = Freq)) + geom_line()
ggplot(typefreq , aes( x = Freq ,  y = type)) + geom_line()
ggplot(typefreq , aes( x = type ,  y = Freq)) + geom_col()
knitr::opts_chunk$set(echo = TRUE)
dataset = read.csv("/home/sanket/CollegeNotes/EDA/Datasets/stack-overflow-developer-survey-2022/survey_results_schema.csv")
names(dataset)
search()
# install.packages("ggplot2")
library(ggplot2)
library(dplyr)
search()
head(dataset)
str(dataset)
dim(dataset)
names(dataset)
str(dataset)
print(as.factor(dataset$qid))
library(dplyr)
data_mod = dataset %>% mutate(qfreq = qid)
data_mod = data_mod %>% select(qid,qfreq,qname,question,force_resp,type,selector)
head(data_mod)
questionfreq = as.factor(data_mod$qfreq)
levels(questionfreq)
table(questionfreq)
questionfreq = as.data.frame(table(questionfreq))
print(questionfreq)
data_mod %>% filter(qid == "QID289")
str(dataset)
str(data_mod)
library(ggplot2)
class(questionfreq$questionfreq)
class(questionfreq$Freq)
questionfreq$questionfreq = as.numeric(questionfreq$questionfreq)
questionfreq$questionfreq
table(questionfreq)
questionfreq = as.data.frame(questionfreq)
head(questionfreq)
questionfreq = questionfreq %>% rename(qid = questionfreq)
head(questionfreq)
str(dataset)
typefreq = as.factor(data_mod$type)
typefreq = as.data.frame(table(typefreq))
typefreq
head(data_mod)
ggplot(questionfreq , aes(x= qid , y = Freq)) + geom_line()
typefreq = typefreq %>% rename( type = typefreq )
typefreq$type = as.numeric(typefreq$type)
print(typefreq)
ggplot(typefreq , aes( x = type ,  y = Freq)) + geom_line()
ggplot(typefreq , aes( x = Freq ,  y = type)) + geom_line()
ggplot(typefreq , aes( x = type ,  y = Freq)) + geom_col()
ggplot(questionfreq , aes( x = qid ,  y = Freq)) + geom_col()
ggplot(typefreq , aes( x = type ,  y = Freq , label = Freq)) + geom_col()
ggplot(typefreq , aes( x = type ,  y = Freq , )) + geom_col() + geom_text(aes( label = Freq), vjust = -0.2)
ggplot(questionfreq , aes(x= qid , y = Freq)) + geom_point()
